[project]
name = "data-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "sanyam jain", email = "samyakjain9759545711@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "dotenv>=0.9.9",
    "langchain>=1.4.0",
    "langchain-openai>=1.6.0",
    "langgraph>=1.2.11",
    "pydantic>=2.13.5",
]

[project.scripts]
data-agent = "data_agent:main"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"
