from operator import add

from pydantic import BaseModel, Field
from typing import Annotated, Literal

class AgentSchema(BaseModel):
    messages: Annotated[list, add] = Field(..., description="List of messages from the agent.")
    user_question: str = Field(..., description="The original question asked by the user.")
    curated_ques : str = Field(..., description="Curated question from the agent.")
    prompt_query_context : str = Field(..., description="Detailed prompt with SQL DB context that will help agent to generate the SQL query")
    generated_sql_query : str = Field(..., description="The SQL query generated by the agent.")
    is_safe_sql_response : Literal['Yes', 'No'] = Field(..., description="Indicates whether the generated SQL query is safe or not.")
    comments : str = Field(..., description="Comments or feedback provided by the agent regarding the safety of the SQL query.")
    sql_query_expected_result : str = Field(..., description="The expected result of the generated SQL query.")
    final_answer : Annotated[list, add] = Field(..., description="The final answer(s) generated by the agent after executing the SQL query.")


class JudgeSchema(BaseModel):
    answer : Literal['Yes', 'No'] = Field(..., description="Indicates whether the final answer is correct or not.")
    comments : str = Field(..., description="Comments or feedback provided by the judge regarding the final answer.")


    