from operator import add

from pydantic import BaseModel, Field
from typing import Annotated, Literal

class AgentSchema(BaseModel):
    messages: Annotated[list, add] = Field(..., description="List of messages from the agent.")
    curated_ques : str = Field(..., description="Curated question from the agent.")
    prompt_query_context : str = Field(..., description="Detailed prompt with SQL DB context that will help agent to generate the SQL query")
    is_safe : Literal['Yes', 'No'] = Field(..., description="Indicates whether the generated SQL query is safe or not.")
    genrated_sql_query : str = Field(..., description="The SQL query generated by the agent.")
    sql_query_expected_result : str = Field(..., description="The expected result of the generated SQL query.")
    final_answer : str = Field(..., description="The final answer generated by the agent after executing the SQL query.")
    